name: fish_recognition_mobile_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  tflite: ^1.1.2
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/icon1.png
    - assets/labels.txt
    - assets/model.tflite
    - assets/

  fonts:
    - family: Manrope
      fonts:
        - asset: fonts\Manrope-VariableFont_wght.ttf

  uses-material-design: true
